server:
  port: 8085
feign:
  okhttp:
    enabled: true
  sentinel:
    enabled: true
hm:
  swagger:
    title: 交易服务接口文档
    desc: 交易服务接口文档
    controller:
      name: com.hmall.trade.controller
  db:
    database: hm-trade
    un: root
spring:
  rabbitmq:
    host: 192.168.80.130
    port: 5672
    virtual-host: /hmall
    username: hmall
    password: 123