server:
  port: 8082
feign:
  okhttp:
    enabled: true
  sentinel:
    enabled: true
hm:
  swagger:
    title: 购物车服务接口文档
    desc: 购物车服务接口文档
    controller:
      name: com.hmall.cart.controller
  db:
    database: hm-cart
    un: root
spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8090
      http-method-specify: true