server:
  port: 8081
hm:
  swagger:
    title: 商品服务接口文档
    desc: 商品服务接口文档
    controller:
      name: com.hmall.item.controller
  db:
    database: hm-item
    un: root
feign:
  okhttp:
    enabled: true
  sentinel:
    enabled: true